- name: Ensuring Ubuntu multiverse repo is enabled
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu {{ OS_DISTRO_RELEASE }} multiverse"
    state: present

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist

- name: Install Deb Packages
  apt: pkg={{ item.packages }} state=present
  with_items:
    - packages:
        - bash-completion
        - containerd.io
        - docker-ce
        - docker-ce-cli
        - git
        - htop
        - mc
        - tig
        - vim
        - virtualbox

- name: Install Snap Packages
  snap: name={{ item.names }} state=present
  with_items:
    - names:
        - chromium
        - code
        - dbeaver-ce
        - postman
        - spotify
        - vlc
        - zoom-client

- name: Download kubectl
  get_url:
    url: https://dl.k8s.io/release/{{ KUBECTL_VERSION }}/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '775'

# - name: Copy config files
#   copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
#   with_items:
#     - { src: 'files/home/user/.bash_aliases', dest: '/etc/profile.d/00-aliases.sh' }
#     - { src: 'files/home/user/.bashrc', dest: '~/.bashrc' }
#     - { src: 'files/home/user/.gitconfig', dest: '~/.gitconfig' }
#     - { src: 'files/home/user/.vimrc', dest: '~/.vimrc' }
